name: Deploy to AWS ECR and Elastic Beanstalk
on:
  push:
    branches:
      - main

env:
  AWS_REGION: us-east-1
  ECR_REPOSITORY_NAME: ecreb-repo
  EB_APPLICATION_NAME: ecreb-app
  EB_ENVIRONMENT_NAME: ecreb-dev

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Create ECR Repository
        run: |
          aws ecr create-repository --repository-name ${{ env.ECR_REPOSITORY_NAME }}

      - name: Deploy to Elastic Beanstalk
        run: |
          aws elasticbeanstalk create-application-version --application-name ${{ env.EB_APPLICATION_NAME }} --version-label $GITHUB_SHA --source-bundle S3Bucket=$GITHUB_REPOSITORY,S3Key=$GITHUB_SHA.zip
          aws elasticbeanstalk update-environment --application-name ${{ env.EB_APPLICATION_NAME }} --environment-name ${{ env.EB_ENVIRONMENT_NAME }} --version-label $GITHUB_SHA
